# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

complexity:
  ComplexMethod:
    active: false
  LongMethod:
    active: false
  TooManyFunctions:
    active: false
  ComplexCondition:
    active: false
exceptions:
  SwallowedException:
    active: false
  TooGenericExceptionThrown:
    active: false
formatting:
  Indentation:
    continuationIndentSize: 8
  ParameterListWrapping:
    indentSize: 4
  MaximumLineLength:
    active: false
style:
  ForbiddenComment:
    active: false
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  ReturnCount:
    active: false
