# IntelliJ Platform Artifacts Repositories
# -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

pluginGroup = org.jetbrains
pluginName = IDE Features Suggester
projectMajorVersion = 243
pluginSinceBuild = 243
pluginUntilBuild = 253.*
# Plugin Verifier integration -> https://github.com/JetBrains/gradle-intellij-plugin#plugin-verifier-dsl
# See https://jb.gg/intellij-platform-builds-list for available build versions
pluginVerifierIdeVersions = IU-243.21565.129

platformType = IU
platformVersion = 243.21565.193
platformDownloadSources = true
platformPlugins = java, JavaScript, Pythonid:243.21565.193, training:243.21565.204

# Gradle Releases -> https://github.com/gradle/gradle/releases
gradleVersion = 7.3

# Opt-out flag for bundling Kotlin standard library.
# See https://kotlinlang.org/docs/reference/using-gradle.html#dependency-on-the-standard-library for details.
kotlin.stdlib.default.dependency = false
kotlin.code.style = official
