# IntelliJ Platform Artifacts Repositories
# -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

pluginGroup = org.jetbrains
pluginName = IDE Features Suggester
projectMajorVersion = 233
pluginSinceBuild = 233
pluginUntilBuild = 233.*
# Plugin Verifier integration -> https://github.com/JetBrains/gradle-intellij-plugin#plugin-verifier-dsl
# See https://jb.gg/intellij-platform-builds-list for available build versions
pluginVerifierIdeVersions = IU-233.11799.196

platformType = IU
platformVersion = 233-EAP-SNAPSHOT
platformDownloadSources = true
platformPlugins = java, Kotlin, JavaScript, Pythonid:233.11799.241, training:233.11799.172

# Gradle Releases -> https://github.com/gradle/gradle/releases
gradleVersion = 7.3

# Opt-out flag for bundling Kotlin standard library.
# See https://kotlinlang.org/docs/reference/using-gradle.html#dependency-on-the-standard-library for details.
kotlin.stdlib.default.dependency = false
kotlin.code.style = official
